# Generated by Django 4.0.2 on 2022-03-23 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, default='', null=True, upload_to='static/images/')),
                ('date_of_birth', models.DateField(default='2021-12-01')),
                ('photographer', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('hobbies', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('phone', models.IntegerField(blank=True, default=0, null=True)),
                ('website', models.URLField(blank=True, default='', null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
