# Generated by Django 4.0.2 on 2022-03-23 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='photographer',
            new_name='photographers',
        ),
    ]
