# Generated by Django 4.0.2 on 2022-05-02 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_alter_category_options_alter_photo_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='like',
            new_name='likes',
        ),
    ]
